# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 23.1.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.7+
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pdm run duty test
        pass_filenames: false
        language: system
        types: [python]
